export const INSTITUTION_LIST_REQUEST = "INSTITUTION_LIST_REQUEST";
export const INSTITUTION_LIST_SUCCESS = "INSTITUTION_LIST_SUCCESS";
export const INSTITUTION_LIST_FAIL = "INSTITUTION_LIST_FAIL";

export const INSTITUTION_EDIT_REQUEST = "INSTITUTION_EDIT_REQUEST";
export const INSTITUTION_EDIT_SUCCESS = "INSTITUTION_EDIT_SUCCESS";
export const INSTITUTION_EDIT_FAIL = "INSTITUTION_EDIT_FAIL";

export const INSTITUTION_DELETE_REQUEST = "INSTITUTION_DELETE_REQUEST";
export const INSTITUTION_DELETE_SUCCESS = "INSTITUTION_DELETE_SUCCESS";
export const INSTITUTION_DELETE_FAIL = "INSTITUTION_DELETE_FAIL";

export const INSTITUTION_CREATE_REQUEST = "INSTITUTION_CREATE_REQUEST";
export const INSTITUTION_CREATE_SUCCESS = "INSTITUTION_CREATE_SUCCESS";
export const INSTITUTION_CREATE_FAIL = "INSTITUTION_CREATE_FAIL";
export const INSTITUTION_CREATE_RESET = "INSTITUTION_CREATE_RESET";

export const INSTITUTION_UPDATE_REQUEST = "INSTITUTION_UPDATE_REQUEST";
export const INSTITUTION_UPDATE_SUCCESS = "INSTITUTION_UPDATE_SUCCESS";
export const INSTITUTION_UPDATE_FAIL = "INSTITUTION_UPDATE_FAIL";
export const INSTITUTION_UPDATE_RESET = "INSTITUTION_UPDATE_RESET";

export const ADD_INSTITUTION = "ADD_INSTITUTION";
export const GET_INSTITUTION = "GET_INSTITUTION";
export const LOAD_INSTITUTION = "LOAD_INSTITUTION";
export const DELETE_INSTITUTION = "DELETE_INSTITUTION";
export const EDIT_INSTITUTION = "EDIT_INSTITUTION";
export const FAIL_INSTITUTION = "FAIL_INSTITUTION";