export const LOGIN_MODERATOR = "LOGIN_MODERATOR";
export const AUTH_MODERATOR = "AUTH_MODERATOR";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOAD_MODERATOR = "LOAD_MODERATOR";
export const FAIL_MODERATOR = "FAIL_MODERATOR";